package com.br.foodbridge.domain.enums

enum class TipoNotificacao {
    DOACAO_REIVINDICADA,
    REIVINDICACAO_APROVADA,
    REIVINDICACAO_REPROVADA,
    COLETA_AGENDADA,
    COLETA_COMPLETA,
    CORRESPONDENCIA,
    DOCUMENTO_VERIFICADO,
    DOCUMENTO_REJEITADO,
    DOCUMENTO_REJEITADO_APROVADO,
    CONTA_VERIFICADO,
    CONTA_REJEITADO,
    ALERTA_SISTEMA,
}