# Dados do banco
spring.datasource.url=jdbc:postgresql://localhost:5432/foodbridge
spring.datasource.username=foodbridge
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Nome da aplicação
spring.application.name=foodbridge

jwt.secret=ccG1OunrHrA/g5ks25lztX/PCTdRHxW2UF4UvqZsZQs=
jwt.expiration=86400000
app.admin.email=admin@foodbridge.com
app.admin.password=admin123